language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
  - export PIP_INDEX_URL=https://simple.crate.io/
  - export DJANGO_SETTINGS_MODULE=appconf.test_settings
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
before_script:
  - flake8 appconf --ignore=E501
script:
  - coverage run --branch --source=appconf `which django-admin.py` test appconf
  - coverage report --omit=appconf/test*
env:
  - DJANGO=1.3.1
  - DJANGO=1.4
branches:
  only:
    - develop
